<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerEFHWn7f\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerEFHWn7f/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerEFHWn7f.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerEFHWn7f\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerEFHWn7f\App_KernelDevDebugContainer([
    'container.build_hash' => 'EFHWn7f',
    'container.build_id' => 'd324e183',
    'container.build_time' => 1580421038,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerEFHWn7f');
